# Generated by Django 4.2.5 on 2023-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(default='https://i.ytimg.com/vi/VdcyC76ba6w/maxresdefault.jpg'),
            preserve_default=False,
        ),
    ]
