# Generated by Django 4.2.5 on 2023-10-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0003_video_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='background_image_url',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='description',
        ),
    ]
