# Generated by Django 4.2.5 on 2024-02-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0002_alter_channel_title_alter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='watched',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default='00:00:00', max_length=100),
            preserve_default=False,
        ),
    ]
