# Generated by Django 4.2.5 on 2023-10-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_date',
            field=models.DateTimeField(default='2023-10-08'),
            preserve_default=False,
        ),
    ]
