# Generated by Django 4.2.5 on 2024-02-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0003_alter_channel_title_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='wallpaper',
            field=models.URLField(null=True),
        ),
    ]
