# Generated by Django 4.2.5 on 2024-02-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0003_remove_video_description_remove_video_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
