# Generated by Django 4.2.5 on 2024-02-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0004_alter_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
