# Generated by Django 4.2.5 on 2024-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0005_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default='00:00:00', max_length=100),
            preserve_default=False,
        ),
    ]
