# Generated by Django 4.2.5 on 2024-02-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0005_remove_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='wallpaper',
        ),
    ]
