# Generated by Django 4.2.5 on 2023-10-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0005_remove_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='wallpaper',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
