# Generated by Django 4.2.5 on 2023-10-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0006_video_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='logo',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
