# Generated by Django 4.2.5 on 2024-02-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0006_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
