# Generated by Django 4.2.5 on 2024-02-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0007_video_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.CharField(max_length=100),
        ),
    ]
