# Generated by Django 4.2.5 on 2024-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0008_alter_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='playlist',
            field=models.CharField(default='PLzkTtcbyuIZ-nMOvWVSg_5PV4jjn0sUDp', max_length=100),
            preserve_default=False,
        ),
    ]
