# Generated by Django 4.2.5 on 2024-01-09 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0008_tag_video_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('wallpaper', models.URLField()),
                ('logo', models.URLField()),
                ('tags', models.ManyToManyField(to='meu_aplicativo.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_aplicativo.show')),
            ],
        ),
    ]
