# Generated by Django 4.2.5 on 2024-01-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0009_show_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
