# Generated by Django 4.2.5 on 2024-02-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0010_batch_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
