# Generated by Django 4.2.5 on 2024-01-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0010_episode_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='thumbnail',
            field=models.URLField(default='link'),
            preserve_default=False,
        ),
    ]
