# Generated by Django 4.2.5 on 2024-01-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0012_show_description_show_rating_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.CharField(default='As famosas pedras pictóricas de Gotland são como as pedras rúnicas vikings da Escandinávia, mas elas têm imagens e menos runas.', max_length=130),
            preserve_default=False,
        ),
    ]
