# Generated by Django 4.2.5 on 2024-01-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0013_episode_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='description',
        ),
    ]
