# Generated by Django 4.2.5 on 2024-02-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0014_remove_episode_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='channel',
            new_name='company',
        ),
    ]
