# Generated by Django 4.2.5 on 2024-02-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0015_rename_channel_company_rename_video_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('wallpaper', models.URLField()),
                ('logo', models.URLField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField()),
                ('published_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_aplicativo.channel')),
            ],
        ),
    ]
