# Generated by Django 4.2.5 on 2024-02-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0016_channel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='meu_aplicativo.tag'),
        ),
    ]
