# Generated by Django 4.2.5 on 2024-02-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0017_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
