# Generated by Django 4.2.5 on 2024-02-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0018_video_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
