# Generated by Django 4.2.5 on 2024-02-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0019_alter_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='show',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='company',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='show',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
