# Generated by Django 4.2.5 on 2024-02-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_aplicativo', '0020_remove_episode_show_remove_movie_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='description',
        ),
    ]
